# Generated by Django 5.2.2 on 2025-06-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(error_messages='El texto debe tener max 8 digitos', max_length=8, primary_key=True, serialize=False)),
                ('ape_nom', models.CharField(max_length=80)),
                ('fec_reg', models.DateField()),
                ('fec_sis', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
