# Generated by Django 5.2.3 on 2025-06-17 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prod', models.CharField(max_length=50)),
                ('des_prod', models.TextField(max_length=500)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('stock', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fec_vencim', models.DateField()),
                ('fec_reg', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
